[package]
name = "sept11-datasets"
version = "0.1.0"
edition = "2021"

[[bin]]
path="src/main.rs"
name="sept11-datasets"

[dependencies]
color-eyre = "0.6"
indicatif = "0.17.6"
lava_torrent = "0.11"
sha-1 = "0.9"
thiserror = "1.0.23"
url = "2.4.1"
